### ISSUE TITLE
Check if directory exists

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/file-api#13]
An endpoint that checks if a specified directory exists.

- Verb: `GET`
- Path: `/dir/exists`

Query parameters:
| Name | Value | Default value | Description |
| --- | --- | --- | --- |
| `path` | string | **required** | A path to a directory which existence should be checked |

Responses:
- `204 No Content` - when the directory exists we can simply return `204` to say "found it". No need to send any additional data.
- `404 Not Found` - when couldn't find the directory or if the path is pointing to a file.
- `400 Bad Request` - when the path is invalid.

**Comment by lansolo99** [comment]
@Xkonti Hi, useful tiny API! I'd like to handle this one if you're up to.

**Comment by Xkonti** [comment]
@lansolo99 Go for it!
