### ISSUE TITLE
Create a directory

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/file-api#14]
An endpoint that creates an empty directory.

- Verb: `POST`
- Path: `/dir`

Query parameters:
| Name | Value | Default value | Description |
| --- | --- | --- | --- |
| `path` | string | **required** | A path to a directory which should be created. |

Responses:
- `204 No Content` - when the directory was successfully created.
- `409 Conflict` - when the path is pointing to already existing directory or file.
- `400 Bad Request` - when the path is invalid.

## Extra info
This should create all required parent directories to bring the target directory to existence.

Example: Client requested creation of a directory `/docs/private/hidden/top-secret`, but only the `/docs/private` currently exists. The  `hidden` and then `top-secret` directories should be appropriately created.

**Comment by lansolo99** [comment]
@Xkonti Hello again, 
I'm eager to continue with this one, in the logic order, if you can assign me on. 
Thx!
