### ISSUE TITLE
Check if file exists

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/file-api#19]
An endpoint that checks if the specified file exists.

- Verb: `GET`
- Path: `/file/exists`

Query parameters:
| Name | Value | Default value | Description |
| --- | --- | --- | --- |
| `path` | string | **required** | A path to a file which existence should be checked. |

Responses:
- `204 No Content` - when the file exists.
- `404 Not Found` - when couldn't find the file or if the path is pointing to a directory.
- `400 Bad Request` - when the path is invalid.

**Comment by SudhanshuJoshi09** [comment]
Hi @Xkonti , Can I pick this up ?
