### ISSUE TITLE
Get file size

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/file-api#28]
An endpoint that returns size in bytes of the specified file.

- Verb: `GET`
- Path: `/file/size`

Query parameters:
| Name | Value | Default value | Description |
| --- | --- | --- | --- |
| `path` | string | **required** | A path to a file. |

Responses:
- `200 OK` - when the file exists.
- `404 Not Found` - when couldn't find the file or if the path is pointing to a directory.
- `400 Bad Request` - when the path is invalid.

Returns file's size in bytes in the JSON format:
```json
{
  "size": 12345
}
```

**Comment by protob** [comment]
Hi, Can i implement this endpoint?

**Comment by Xkonti** [comment]
@protob Sure thing! Please remember to also implement simple tests. Here's are some examples:
- Testing the actual endpoint: https://github.com/Xkonti/file-api/blob/main/src/endpoints/file/getFile.test.ts
- Tests for file utilities: https://github.com/Xkonti/file-api/blob/main/src/utils/fileUtils.test.ts

I hope those examples will help you out understanding how things work 🙂 Let me know if you have some questions.

**Comment by protob** [comment]
Thanks,  I heard some nice opinions about ElysiaJS, and i wanted to try it. I opened PR with API endpoint with a test.

**Comment by Xkonti** [comment]
ElysiaJS is pretty neat indeed :)
